name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Install Playwright Browsers (for parity tests)
        if: env.RUN_PARITY == 'true'
        run: |
          dotnet build tests/Andy.Tui.Parity.Playwright/Andy.Tui.Parity.Playwright.csproj -c Debug
          bash tests/Andy.Tui.Parity.Playwright/bin/Debug/net8.0/playwright.sh install chromium
      - name: Test
        run: |
          if [ "${RUN_PARITY}" = "true" ]; then
            dotnet test --no-build --verbosity normal
          else
            dotnet test --no-build --verbosity normal --filter FullyQualifiedName!~Andy.Tui.Parity.Playwright
          fi
